# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners
# https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu2004-README.md
# https://github.com/marketplace?type=actions
# https://github.com/actions/checkout
# https://github.com/actions/setup-java
# https://github.com/actions/setup-node
# https://github.com/actions/setup-go
# https://github.com/actions-rs/cargo

on:
  push:
    branches:
      - hexo

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: apt
        run: |
          # dpkg -l
          sudo apt-get update
          # 21 minutes !
          # sudo apt-get dist-upgrade -y
          # sudo DEBIAN_FRONTEND=noninteractive ACCEPT_EULA=Y apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --allow-downgrades --allow-remove-essential --allow-change-held-packages dist-upgrade
          sudo apt-get install -y --no-install-recommends ca-certificates curl git g++ xz-utils libsass-dev

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/checkout@v2
        with:
          clean: true
          lfs: false
          persist-credentials: true

      - name: shell
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
          # https://github.com/settings/tokens
          GITHUB_DEPLOY_KEY: ${{ secrets.GITHUB_DEPLOY_KEY }}
        run: |
          printenv | sort

          mkdir -p ~/.ssh/
          echo "$GITHUB_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git config --global user.email "songdongsheng@live.cn"
          git config --global user.name "宋冬生"

          git submodule sync --recursive
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive

          npm version
          npm install --unsafe-perm --global hexo@4.2.1
          npm install --unsafe-perm
          # npm list

          hexo deploy || true
